---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
    driver:
      box: opentable/win-2012r2-standard-amd64-nocm
      gui: true
    transport:
      name: winrm
      elevated: true
  - name: ubuntu-14.04

suites:
#  - name: chef-server
#    run_list:
#      - recipe[shavlik::hosts]
#      - recipe[shavlik::install_chef_server]
#    excludes:
#      - windows-2012r2
#    driver:
#      vm_hostname: chef
#      network:
#        - ['private_network', {ip: '33.33.0.10'}]
#      customize:
#        memory: 2048
#    attributes:
#      chef_server:
#        fqdn: chef
#        install_dir: /tmp/

  - name: shavlik
    run_list:
      - recipe[shavlik::hosts]
    excludes:
      - ubuntu-14.04
    driver:
      vm_hostname: shavlik
      network:
        - ['private_network', {ip: '33.33.0.20'}]
    verifier:
      inspec_tests:
        - https://github.com/dev-sec/windows-patch-benchmark
    attributes:

  - name: unpatched
    run_list:
      - recipe[shavlik::hosts]
    excludes:
      - ubuntu-14.04
    driver:
      vm_hostname: unpatched
      network:
        - ['private_network', {ip: '33.33.0.30'}]
    verifier:
      inspec_tests:
        - https://github.com/dev-sec/windows-patch-benchmark
    attributes:
