---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
    driver:
      box: mwrock/Windows2012R2
      gui: true
    transport:
      name: winrm
      elevated: true
  - name: windows-2012r2-older
    driver:
      box: opentable/win-2012r2-standard-amd64-nocm
      gui: true
    transport:
      name: winrm
      elevated: true
  - name: ubuntu-14.04

suites:
  - name: shavlik
    excludes:
      - windows-2012r2-older
      - ubuntu-14.04
    run_list:
      - recipe[shavlik::hosts]
      - recipe[shavlik::server]
      - recipe[shavlik::scan]
    driver:
      vm_hostname: shavlik
      network:
        - ['private_network', {ip: '33.33.0.20'}]
    verifier:
      inspec_tests:
        - https://github.com/dev-sec/windows-patch-benchmark
    attributes:

  - name: unpatched
    excludes:
      - windows-2012r2
      - ubuntu-14.04
    run_list:
      - recipe[shavlik::hosts]
      - recipe[shavlik::client]
    driver:
      vm_hostname: unpatched
      network:
        - ['private_network', {ip: '33.33.0.30'}]
    verifier:
      inspec_tests:
        - https://github.com/dev-sec/windows-patch-benchmark
    attributes:

  - name: chef
    excludes:
      - windows-2012r2
      - windows-2012r2-older
    run_list:
      - recipe[shavlik::hosts]
      - recipe[shavlik::install_chef_server]
    driver:
      vm_hostname: chef
      network:
        - ['private_network', {ip: '33.33.0.10'}]
