---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
    driver:
      box: opentable/win-2012r2-standard-amd64-nocm
      gui: true
    transport:
      name: winrm
      elevated: true

suites:
  - name: shavlik
    run_list:
      - recipe[shavlik::default]
    verifier:
      inspec_tests:
        - https://github.com/dev-sec/windows-patch-benchmark
    attributes:

  - name: unpatched
    run_list:
      - recipe[shavlik::default]
    verifier:
      inspec_tests:
        - https://github.com/dev-sec/windows-patch-benchmark
    attributes:
